# docker compose version
version: "3.8"

# 利用する コンテナ 一覧
services:
  # composer 実行用
  lib:
    # 管理コンテナ名
    container_name: ${APP_NAME}-composer
    # Dockerファイルにて 定義
    build: ./docker/php
    # 場所
    volumes:
      - ./kintone-laravel-model/:/var/www/html
    # 環境設定値設定 TODO:env以外は最終的には使わない？
    environment:
      # アプリ系
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV:-local}
  # example-laravelよう
  app:
    # 管理コンテナ名
    container_name: ${APP_NAME}-app
    # Dockerファイルにて 定義
    build: ./docker/php
    # ホスト名指定
    hostname: app
    # 場所
    volumes:
      - ./example-laravel/:/var/www/html
      # TODO: composer開発の composerにしたい プロジェクトをマウントする形がベスト??
    # 利用ポート
    ports:
      # TODO: フロントエンド vite使うってことで bladeで作るけど...
      - ${VITE_PORT:-5173}:5173
    # 環境設定値設定
    environment:
      # アプリ系
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - APP_ENV=${APP_ENV:-local}
      # TODO: kintoneの情報
  # WEBサーバー
  web:
    # 管理コンテナ名
    container_name: ${APP_NAME}-web
    # Dockerファイルにて 定義
    build: ./docker/nginx
    # 利用ポート
    ports:
      - ${WEB_USER_PORT:-8080}:80
    # 依存関係
    depends_on:
      - app
    # 場所
    volumes:
      - ./example-laravel/:/var/www/html
    # 環境設定値
    environment:
      # nginx 対応 ホスト名
      - PHP_APP_HOST=app
    # コマンド
    # defaut.conf内容書き換え
    command: /bin/sh -c "envsubst '$$PHP_APP_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
